### ISSUE TITLE
Project still alive ?

### ISSUE THREAD

**Issue by sybaris** [kevinjpetersen/BlazorQuery#2]
Hi 

The project seems interesting, but I do not see any activity from about 1 year.
And the solution use preview version of blazor, and have not been updated.

Do you plan to continue some work on this project or not ?

Regards,
Sybaris

**Comment by kevinjpetersen** [comment]
Hi Sybaris

My plan has always been to finish this project, and my plan is still to do so. However as you mentioned there hasn't been any activity for about a year. This is mostly due to me going from a normal job to now self employed which made the available time to work on open source projects almost non existent.

Hopefully I can start some more work on this soon, and as always, I always appreciate and accept PR's :)

Thanks for your interest in the project!

**Comment by kevinjpetersen** [comment]
Closing this as it's answered :)
